CREATE DATABASE QLSV_TC
GO

USE QLSV_TC
GO

CREATE TABLE KHOA(
	MAKHOA nvarchar(10) primary key,
	TENKHOA nvarchar(50),
	DONGIA float
)
GO

CREATE TABLE CHUYENNGANH(
	MACN nvarchar(10) primary key,
	TENCN nvarchar(50),
	MAKHOA nvarchar(10)
)
GO

CREATE TABLE CTCHUYENNGANH(
	MACTCN int identity(6000, 1) primary key,
	MACN nvarchar(10),
	MAMH nvarchar(10)
)
GO

CREATE TABLE LOP(
	MALOP nvarchar(10) primary key,
	MACN nvarchar(10)
)
GO

CREATE TABLE SINHVIEN(
	MASV nvarchar(15) primary key,
	HO nvarchar(50),
	TEN nvarchar(10),
	MALOP nvarchar(10),
	PHAI bit, --FALSE: NAM, TRUE: NỮ
	NGAYSINH date,
	DIACHI nvarchar(100),
	DANGNGHIHOC bit,
	TENTAIKHOAN nvarchar(20)
)
GO

CREATE TABLE MONHOC(
	MAMH nvarchar(10) primary key,
	TENMH nvarchar(100),
	HOCKY int,
	SOTINCHI int
)
GO

CREATE TABLE GIANGVIEN(
	MAGV nvarchar(10) primary key,
	MAKHOA nvarchar(10),
	HO nvarchar(50),
	TEN nvarchar(10),
	HOCHAM nvarchar(20)
)
GO

CREATE TABLE LOPHOCPHAN(
	MALHP int identity(1000, 1) primary key,
	NIENKHOA nvarchar(9),
	HOCKY int,
	MAMH nvarchar(10),
	MAGV nvarchar(10),
	MACN nvarchar(10),
	HUYLOP bit
)
GO

CREATE TABLE DANGKY(
	MADK int identity(2000, 1) primary key,
	MASV nvarchar(15),
	HOCKY int
)
GO

CREATE TABLE CTDANGKY(
	MACTDK int identity(3000, 1) primary key,
	MALHP int,
	MADK int
)
GO

CREATE TABLE PHIEUTHU(
	MAPT int identity(4000, 1) primary key,
	MASV nvarchar(15),
	NIENKHOA nvarchar(9),
	HOCKY int
)
GO

CREATE TABLE CTPHIEUTHU(
	MACTPT int identity(5000, 1) primary key,
	MAPT int,
	NGAYDONG datetime DEFAULT GETDATE(),
	SOTIENDONG float
)
GO

CREATE TABLE NGUOIDUNG(
	TENTAIKHOAN nvarchar(20) primary key,
	MATKHAU nvarchar(20),
	QUYEN nvarchar(20)
)
GO

ALTER TABLE LOP ADD CONSTRAINT FK_LOP_CHUYENNGANH FOREIGN KEY (MACN) REFERENCES CHUYENNGANH(MACN)

ALTER TABLE CHUYENNGANH ADD CONSTRAINT FK_CHUYENNGANH_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE CTCHUYENNGANH ADD CONSTRAINT FK_CTCHUYENNGANH_CHUYENNGANH FOREIGN KEY (MACN) REFERENCES CHUYENNGANH(MACN)
ALTER TABLE CTCHUYENNGANH ADD CONSTRAINT FK_CTCHUYENNGANH_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE GIANGVIEN ADD CONSTRAINT FK_GIANGVIEN_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE PHIEUTHU ADD CONSTRAINT FK_PHIEUTHU_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)

ALTER TABLE CTPHIEUTHU ADD CONSTRAINT FK_CTPHIEUTHU_PHIEUTHU FOREIGN KEY (MAPT) REFERENCES PHIEUTHU(MAPT)

ALTER TABLE DANGKY ADD CONSTRAINT FK_DANGKY_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)

ALTER TABLE CTDANGKY ADD CONSTRAINT FK_CTDANGKY_DANGKY FOREIGN KEY (MADK) REFERENCES DANGKY(MADK)
ALTER TABLE CTDANGKY ADD CONSTRAINT FK_CTDANGKY_LOPHOCPHAN FOREIGN KEY (MALHP) REFERENCES LOPHOCPHAN(MALHP)

ALTER TABLE LOPHOCPHAN ADD CONSTRAINT FK_LOPHOCPHAN_GIANGVIEN FOREIGN KEY (MAGV) REFERENCES GIANGVIEN(MAGV)
ALTER TABLE LOPHOCPHAN ADD CONSTRAINT FK_LOPHOCPHAN_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
ALTER TABLE LOPHOCPHAN ADD CONSTRAINT FK_LOPHOCPHAN_CHUYENNGANH FOREIGN KEY (MACN) REFERENCES CHUYENNGANH(MACN)

ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SINHVIEN_NGUOIDUNG FOREIGN KEY (TENTAIKHOAN) REFERENCES NGUOIDUNG(TENTAIKHOAN)
ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
