CREATE DATABASE QLSV_TC
GO

USE QLSV_TC
GO

CREATE TABLE KHOA(
	MAKHOA nvarchar(10) primary key,
	TENKHOA nvarchar(50),
	DONGIA float
)
GO

CREATE TABLE LOP(
	MALOP nvarchar(10) primary key,
	CHUYENNGANH nvarchar(50),
	MAKHOA nvarchar(10)
)
GO

CREATE TABLE SINHVIEN(
	MASV nvarchar(15) primary key,
	HO nvarchar(50),
	TEN nvarchar(10),
	MALOP nvarchar(10),
	MAKHOA nvarchar(10),
	PHAI bit, --FALSE: NAM, TRUE: NỮ
	NGAYSINH date,
	DIACHI nvarchar(100),
	DANGNGHIHOC bit,
	PASSWORD nvarchar(40)
)
GO

CREATE TABLE MONHOC(
	MAMH nvarchar(10) primary key,
	TENMH nvarchar(100),
	SOTINCHI int
)
GO

CREATE TABLE GIANGVIEN(
	MAGV nvarchar(10) primary key,
	MAKHOA nvarchar(10),
	HO nvarchar(50),
	TEN nvarchar(10),
	HOCHAM nvarchar(20)
)
GO

CREATE TABLE LOPHOCPHAN(
	MALHP int identity(1000, 1) primary key,
	NIENKHOA nvarchar(9),
	HOCKY int,
	MAMH nvarchar(10),
	MAGV nvarchar(10),
	MAKHOA nvarchar(10),
	HUYLOP bit,
)
GO

CREATE TABLE DANGKY(
	MADK int identity(2000, 1) primary key,
	MALHP int,
	MASV nvarchar(15),
	HUYDANGKY bit
)
GO

CREATE TABLE PHIEUTHU(
	MAPT int identity(3000, 1) primary key,
	MASV nvarchar(15),
	NIENKHOA nvarchar(9),
	HOCKY int,
	NGAYDONG datetime DEFAULT GETDATE(),
	SOTIENDONG int
)
GO

ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SINHVIEN_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
ALTER TABLE LOP ADD CONSTRAINT FK_LOP_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
ALTER TABLE LOPHOCPHAN ADD CONSTRAINT FK_LOPHOCPHAN_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
ALTER TABLE GIANGVIEN ADD CONSTRAINT FK_GIANGVIEN_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE PHIEUTHU ADD CONSTRAINT FK_PHIEUTHU_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)
ALTER TABLE DANGKY ADD CONSTRAINT FK_DANGKY_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)

ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

ALTER TABLE DANGKY ADD CONSTRAINT FK_DANGKY_LOPHOCPHAN FOREIGN KEY (MALHP) REFERENCES LOPHOCPHAN(MALHP)

ALTER TABLE LOPHOCPHAN ADD CONSTRAINT FK_LOPHOCPHAN_GIANGVIEN FOREIGN KEY (MAGV) REFERENCES GIANGVIEN(MAGV)

ALTER TABLE LOPHOCPHAN ADD CONSTRAINT FK_LOPHOCPHAN_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)