ALTER TABLE SINHVIEN ADD MAKHOA NVARCHAR(10)
ALTER TABLE LOP DROP COLUMN TENLOP

ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SINHVIEN_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

ALTER TABLE MONHOC DROP COLUMN SOTIETLT
ALTER TABLE MONHOC DROP COLUMN SOTIETTH

ALTER TABLE DANGKY DROP COLUMN DIEM_CC
ALTER TABLE DANGKY DROP COLUMN DIEM_GK
ALTER TABLE DANGKY DROP COLUMN DIEM_CK
EXEC sp_rename 'DANGKY.MALTC', 'MALHP', 'COLUMN';

ALTER TABLE LOPHOCPHAN ALTER COLUMN MALHP int NOT NULL
ALTER TABLE LOPHOCPHAN ADD PRIMARY KEY (MALHP)



ALTER TABLE DANGKY ADD CONSTRAINT FK_DANGKY_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV)
ALTER TABLE DANGKY ADD CONSTRAINT FK_DANGKY_LOPHOCPHAN FOREIGN KEY (MALHP) REFERENCES LOPHOCPHAN(MALHP)
ALTER TABLE LOPHOCPHAN ADD CONSTRAINT FK_LOPHOCPHAN_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
ALTER TABLE LOPHOCPHAN ADD CONSTRAINT FK_LOPHOCPHAN_GIANGVIEN FOREIGN KEY (MAGV) REFERENCES GIANGVIEN(MAGV)

ALTER TABLE TINCHI ADD CONSTRAINT FK_TINCHI_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)