USE QLSV_TC
GO

CREATE PROCEDURE sp_CTCHUYENNGANH_insert (
	@MACN nvarchar(10),
	@MAMH nvarchar(10)
)
AS
BEGIN
	INSERT INTO CTCHUYENNGANH (MACN, MAMH)
	VALUES (@MACN, @MAMH)
END
GO

CREATE PROCEDURE sp_CTCHUYENNGANH_update (
	@MACTCN int,
	@MACN nvarchar(10),
	@MAMH nvarchar(10)
)
AS
BEGIN
	UPDATE CTCHUYENNGANH
	SET MACN = @MACN, MAMH = @MAMH
	WHERE MACTCN = @MACTCN
END
GO

CREATE PROCEDURE sp_CTCHUYENNGANH_delete (
	@MACTCN int
)
AS
BEGIN
	DELETE FROM CTCHUYENNGANH WHERE MACTCN = @MACTCN
END
GO

CREATE PROCEDURE sp_CTCHUYENNGANH_delete_by_mamh (
	@MAMH nvarchar(10)
)
AS
BEGIN
	DELETE FROM CTCHUYENNGANH WHERE MAMH = @MAMH
END
GO

CREATE PROCEDURE sp_CTCHUYENNGANH_select_all
AS
BEGIN
	SELECT * FROM CTCHUYENNGANH
END
GO

CREATE PROCEDURE sp_CTCHUYENNGANH_select_mactcn (
	@MACTCN int
)
AS
BEGIN
	SELECT * FROM CTCHUYENNGANH WHERE MACTCN = @MACTCN
END
GO
