use QLSV_TC
go

create procedure sp_CHUONGTRINHHOC_select_all(
	@MASV nvarchar(15)
)
as
begin
	select MONHOC.MAMH, MONHOC.TENMH, MONHOC.HOCKY, MONHOC.SOTINCHI
	from SINHVIEN INNER JOIN LOP ON SINHVIEN.MALOP = LOP.MALOP
					INNER JOIN CHUYENNGANH ON LOP.MACN = CHUYENNGANH.MACN
					INNER JOIN CTCHUYENNGANH ON CHUYENNGANH.MACN = CTCHUYENNGANH.MACN
					INNER JOIN MONHOC ON CTCHUYENNGANH.MAMH = MONHOC.MAMH
	WHERE SINHVIEN.MASV = @MASV
end
GO

create procedure sp_CHUONGTRINHHOC_find_hocky(
	@MASV nvarchar(15),
	@HOCKY int
)
as
begin
	select MONHOC.MAMH, MONHOC.TENMH, MONHOC.HOCKY, MONHOC.SOTINCHI
	from SINHVIEN INNER JOIN LOP ON SINHVIEN.MALOP = LOP.MALOP
					INNER JOIN CHUYENNGANH ON LOP.MACN = CHUYENNGANH.MACN
					INNER JOIN CTCHUYENNGANH ON CHUYENNGANH.MACN = CTCHUYENNGANH.MACN
					INNER JOIN MONHOC ON CTCHUYENNGANH.MAMH = MONHOC.MAMH
	WHERE SINHVIEN.MASV = @MASV AND MONHOC.HOCKY = @HOCKY
end
go

create procedure sp_CHUONGTRINHHOC_find_tenmh_by_hocky(
	@MASV nvarchar(15),
	@TENMH nvarchar(100),
	@HOCKY int
)
as
begin
	select MONHOC.MAMH, MONHOC.TENMH, MONHOC.HOCKY, MONHOC.SOTINCHI
	from SINHVIEN INNER JOIN LOP ON SINHVIEN.MALOP = LOP.MALOP
					INNER JOIN CHUYENNGANH ON LOP.MACN = CHUYENNGANH.MACN
					INNER JOIN CTCHUYENNGANH ON CHUYENNGANH.MACN = CTCHUYENNGANH.MACN
					INNER JOIN MONHOC ON CTCHUYENNGANH.MAMH = MONHOC.MAMH
	WHERE SINHVIEN.MASV = @MASV AND MONHOC.HOCKY = @HOCKY AND TENMH LIKE N'%' + @TENMH + '%'
end
go

create procedure sp_CHUONGTRINHHOC_find_tenmh(
	@MASV nvarchar(15),
	@TENMH nvarchar(100)
)
as
begin
	select MONHOC.MAMH, MONHOC.TENMH, MONHOC.HOCKY, MONHOC.SOTINCHI
	from SINHVIEN INNER JOIN LOP ON SINHVIEN.MALOP = LOP.MALOP
					INNER JOIN CHUYENNGANH ON LOP.MACN = CHUYENNGANH.MACN
					INNER JOIN CTCHUYENNGANH ON CHUYENNGANH.MACN = CTCHUYENNGANH.MACN
					INNER JOIN MONHOC ON CTCHUYENNGANH.MAMH = MONHOC.MAMH
	WHERE SINHVIEN.MASV = @MASV AND TENMH LIKE N'%' + @TENMH + '%'
end
go

create procedure sp_CHUONGTRINHHOC_by_chuyennganh(
	@MACN nvarchar(10)
)
as
begin
	SELECT MONHOC.*
	FROM CHUYENNGANH INNER JOIN CTCHUYENNGANH ON CHUYENNGANH.MACN = CTCHUYENNGANH.MACN
					INNER JOIN MONHOC ON CTCHUYENNGANH.MAMH = MONHOC.MAMH
	WHERE CHUYENNGANH.MACN = @MACN
end
go

create procedure sp_CHUONGTRINHHOC_not_in_chuyennganh(
	@MACN nvarchar(10)
)
as
begin
	SELECT *
	FROM MONHOC
	WHERE MONHOC.MAMH NOT IN
			(SELECT MONHOC.MAMH
			FROM CHUYENNGANH INNER JOIN CTCHUYENNGANH ON CHUYENNGANH.MACN = CTCHUYENNGANH.MACN
							INNER JOIN MONHOC ON CTCHUYENNGANH.MAMH = MONHOC.MAMH
			WHERE CHUYENNGANH.MACN = @MACN)
end
go

create procedure sp_CHUONGTRINHHOC_find_by_tenmh_chuyennganh(
	@MACN nvarchar(10),
	@TENMH nvarchar(100)
)
as
begin
	SELECT MONHOC.*
	FROM CHUYENNGANH INNER JOIN CTCHUYENNGANH ON CHUYENNGANH.MACN = CTCHUYENNGANH.MACN
					INNER JOIN MONHOC ON CTCHUYENNGANH.MAMH = MONHOC.MAMH
	WHERE CHUYENNGANH.MACN = @MACN AND MONHOC.TENMH LIKE '%' + @TENMH + '%'
end
go

create procedure sp_CHUONGTRINHHOC_find_by_tenmh_not_in_chuyennganh(
	@MACN nvarchar(10),
	@TENMH nvarchar(100)
)
as
begin
	SELECT *
	FROM MONHOC
	WHERE MONHOC.MAMH NOT IN
			(SELECT MONHOC.MAMH
			FROM CHUYENNGANH INNER JOIN CTCHUYENNGANH ON CHUYENNGANH.MACN = CTCHUYENNGANH.MACN
							INNER JOIN MONHOC ON CTCHUYENNGANH.MAMH = MONHOC.MAMH
			WHERE CHUYENNGANH.MACN = @MACN)
		  AND MONHOC.TENMH LIKE '%' + @TENMH + '%'
end
go
