use QLSV_TC
go

create procedure sp_CHUONGTRINHHOC_select_all(
	@MASV nvarchar(15)
)
as
begin
	select MONHOC.MAMH, MONHOC.TENMH, MONHOC.HOCKY, MONHOC.SOTINCHI
	from SINHVIEN INNER JOIN LOP ON SINHVIEN.MALOP = LOP.MALOP
				INNER JOIN CHUYENNGANH ON LOP.MACN = CHUYENNGANH.MACN
				INNER JOIN MONHOC ON CHUYENNGANH.MACN = MONHOC.MACN
	WHERE SINHVIEN.MASV = @MASV
end
GO

create procedure sp_CHUONGTRINHHOC_find_hocky(
	@MASV nvarchar(15),
	@HOCKY int
)
as
begin
	select MONHOC.MAMH, MONHOC.TENMH, MONHOC.HOCKY, MONHOC.SOTINCHI
	from SINHVIEN INNER JOIN LOP ON SINHVIEN.MALOP = LOP.MALOP
				INNER JOIN CHUYENNGANH ON LOP.MACN = CHUYENNGANH.MACN
				INNER JOIN MONHOC ON CHUYENNGANH.MACN = MONHOC.MACN
	WHERE SINHVIEN.MASV = @MASV AND MONHOC.HOCKY = @HOCKY
end
go

create procedure sp_CHUONGTRINHHOC_find_tenmh_by_hocky(
	@MASV nvarchar(15),
	@TENMH nvarchar(100),
	@HOCKY int
)
as
begin
	select MONHOC.MAMH, MONHOC.TENMH, MONHOC.HOCKY, MONHOC.SOTINCHI
	from SINHVIEN INNER JOIN LOP ON SINHVIEN.MALOP = LOP.MALOP
				INNER JOIN CHUYENNGANH ON LOP.MACN = CHUYENNGANH.MACN
				INNER JOIN MONHOC ON CHUYENNGANH.MACN = MONHOC.MACN
	WHERE SINHVIEN.MASV = @MASV AND MONHOC.HOCKY = @HOCKY AND TENMH LIKE N'%' + @TENMH + '%'
end
go

create procedure sp_CHUONGTRINHHOC_find_tenmh(
	@MASV nvarchar(15),
	@TENMH nvarchar(100)
)
as
begin
	select MONHOC.MAMH, MONHOC.TENMH, MONHOC.HOCKY, MONHOC.SOTINCHI
	from SINHVIEN INNER JOIN LOP ON SINHVIEN.MALOP = LOP.MALOP
				INNER JOIN CHUYENNGANH ON LOP.MACN = CHUYENNGANH.MACN
				INNER JOIN MONHOC ON CHUYENNGANH.MACN = MONHOC.MACN
	WHERE SINHVIEN.MASV = @MASV AND TENMH LIKE N'%' + @TENMH + '%'
end
go