USE QLSV_TC
GO

CREATE PROCEDURE sp_NGUOIDUNG_insert(
	@TENTAIKHOAN nvarchar(20),
	@MATKHAU nvarchar(20),
	@QUYEN nvarchar(20)
)
AS
BEGIN
    INSERT INTO NGUOIDUNG (TENTAIKHOAN, MATKHAU, QUYEN)
    VALUES (@TENTAIKHOAN, @MATKHAU, @QUYEN)
END
GO

CREATE PROCEDURE sp_NGUOIDUNG_update(
	@TENTAIKHOAN nvarchar(20),
	@MATKHAU nvarchar(20),
	@QUYEN nvarchar(20)
)
AS
BEGIN
	UPDATE NGUOIDUNG
	SET MATKHAU = @MATKHAU, QUYEN = @QUYEN 
	WHERE TENTAIKHOAN = @TENTAIKHOAN
END
GO

CREATE PROCEDURE sp_NGUOIDUNG_delete(
	@TENTAIKHOAN nvarchar(20)
)
AS
BEGIN
    DELETE FROM NGUOIDUNG
    WHERE TENTAIKHOAN = @TENTAIKHOAN
END
GO

CREATE PROCEDURE sp_NGUOIDUNG_select_all
AS
BEGIN
    SELECT * FROM NGUOIDUNG
END
GO

CREATE PROCEDURE sp_NGUOIDUNG_select_tentaikhoan(
    @TENTAIKHOAN nvarchar(20)
)
AS
BEGIN
    SELECT * FROM NGUOIDUNG WHERE TENTAIKHOAN = @TENTAIKHOAN
END
GO
