USE QLSV_TC
GO

-- INSERT
CREATE PROCEDURE sp_KHOA_insert (
@MAKHOA nvarchar(10),
@TENKHOA nvarchar(50),
@DONGIA float
) AS
BEGIN
INSERT INTO KHOA (MAKHOA, TENKHOA, DONGIA)
VALUES (@MAKHOA, @TENKHOA, @DONGIA)
END
GO

-- UPDATE
CREATE PROCEDURE sp_KHOA_update (
@MAKHOA nvarchar(10),
@TENKHOA nvarchar(50),
@DONGIA float
) AS
BEGIN
UPDATE KHOA SET TENKHOA = @TENKHOA, DONGIA = @DONGIA
WHERE MAKHOA = @MAKHOA
END
GO

-- DELETE
CREATE PROCEDURE sp_KHOA_delete (
@MAKHOA nvarchar(10)
) AS
BEGIN
DELETE FROM KHOA WHERE MAKHOA = @MAKHOA
END
GO

-- SELECT *
CREATE PROCEDURE sp_KHOA_select_all AS
BEGIN
SELECT * FROM KHOA
END
GO

-- SELECT ID
CREATE PROCEDURE sp_KHOA_select_makhoa (
@MAKHOA nvarchar(10)
) AS
BEGIN
SELECT * FROM KHOA WHERE MAKHOA = @MAKHOA
END
GO