CREATE PROCEDURE sp_DANGKY_insert(
	@MADK int,
	@MALTC int,
	@MASV nvarchar(10),
	@DIEM_CC int,
	@DIEM_GK float,
	@DIEM_CK float,
	@HUYDANGKY bit
)
AS
BEGIN
	INSERT INTO DANGKY VALUES (@MADK, @MALTC, @MASV, @DIEM_CC, @DIEM_GK, @DIEM_CK, @HUYDANGKY)
END
GO

CREATE PROCEDURE sp_DANGKY_update(
	@MADK int,
	@MALTC int,
	@MASV nvarchar(10),
	@DIEM_CC int,
	@DIEM_GK float,
	@DIEM_CK float,
	@HUYDANGKY bit
)
AS
BEGIN
	UPDATE DANGKY SET MALTC = @MALTC, MASV = @MASV, DIEM_CC = @DIEM_CC, DIEM_GK = @DIEM_GK, DIEM_CK = @DIEM_CK, HUYDANGKY = @HUYDANGKY WHERE MADK = @MADK
END
GO

CREATE PROCEDURE sp_DANGKY_delete(
	@MADK int
)
AS
BEGIN
	DELETE FROM DANGKY WHERE MADK = @MADK
END
GO

CREATE PROCEDURE sp_DANGKY_select_all
AS
BEGIN
	SELECT * FROM DANGKY
END
GO

CREATE PROCEDURE sp_DANGKY_select_madk(
	@MADK int
)
AS
BEGIN
	SELECT * FROM DANGKY WHERE MADK = @MADK
END
GO
