use QLSV_TC
go

create procedure sp_CHUONGTRINHHOC_select_all(
	@MASV nvarchar(15)
)
as
begin
	select MONHOC.MAMH, MONHOC.TENMH, MONHOC.HOCKY, MONHOC.SOTINCHI
	from SINHVIEN INNER JOIN LOP ON SINHVIEN.MALOP = LOP.MALOP
				INNER JOIN CHUYENNGANH ON LOP.MACN = CHUYENNGANH.MACN
				INNER JOIN MONHOC ON CHUYENNGANH.MACN = MONHOC.MACN
	WHERE SINHVIEN.MASV = @MASV
end
GO

create procedure sp_CHUONGTRINHHOC_find_hocky(
	@MASV nvarchar(15),
	@HOCKY int
)
as
begin
	select MONHOC.MAMH, MONHOC.TENMH, MONHOC.HOCKY, MONHOC.SOTINCHI
	from SINHVIEN INNER JOIN LOP ON SINHVIEN.MALOP = LOP.MALOP
				INNER JOIN CHUYENNGANH ON LOP.MACN = CHUYENNGANH.MACN
				INNER JOIN MONHOC ON CHUYENNGANH.MACN = MONHOC.MACN
	WHERE SINHVIEN.MASV = @MASV AND MONHOC.HOCKY = @HOCKY
end

exec sp_CHUONGTRINHHOC_find_hocky '72DCHT20104', 1