USE QLSV_TC
GO

CREATE PROCEDURE sp_XULYHOCPHI_select_all(
	@MASV nvarchar(15)
)
as
begin
	DECLARE @temp_dongia float
	--Lấy ra đơn giá 1 tín chỉ của khoa sinh viên đang ở
	SELECT @temp_dongia = KHOA.DONGIA
	FROM SINHVIEN INNER JOIN LOP ON SINHVIEN.MALOP = LOP.MALOP
				INNER JOIN CHUYENNGANH ON LOP.MACN = CHUYENNGANH.MACN
				INNER JOIN KHOA ON CHUYENNGANH.MAKHOA = KHOA.MAKHOA
	WHERE SINHVIEN.MASV = @MASV
	--Tính học phí của từng học kỳ sinh viên đang học
	SELECT SINHVIEN.MASV, DANGKY.MADK, DANGKY.HOCKY, SUM(MONHOC.SOTINCHI) as TONGSOTC, @temp_dongia * SUM(MONHOC.SOTINCHI) as HOCPHI
	FROM SINHVIEN INNER JOIN DANGKY ON SINHVIEN.MASV = DANGKY.MASV
				INNER JOIN CTDANGKY ON DANGKY.MADK = CTDANGKY.MADK
				INNER JOIN LOPHOCPHAN ON CTDANGKY.MALHP = LOPHOCPHAN.MALHP
				INNER JOIN MONHOC ON LOPHOCPHAN.MAMH = MONHOC.MAMH
	WHERE SINHVIEN.MASV = @MASV
	GROUP BY SINHVIEN.MASV, DANGKY.MADK, DANGKY.HOCKY
end
go

exec sp_XULYHOCPHI_select_all '72DCHT20104'
go

CREATE PROCEDURE sp_XULYHOCPHI_tonghocphi(
	@MASV nvarchar(15)
)
as
begin
	CREATE TABLE #temp(
		MASV nvarchar(15),
		MADK int,
		HOCKY int,
		TONGSOTC int,
		HOCPHI float
	)

	INSERT INTO #temp
	EXEC sp_XULYHOCPHI_select_all @MASV

	SELECT SUM(HOCPHI) as TONGHOCPHI
	FROM #temp
end
go

sp_XULYHOCPHI_tonghocphi '72DCHT20104'

CREATE PROCEDURE sp_XULYHOCPHI_byhocky(
	@MASV nvarchar(15),
	@HOCKY int
)
as
begin
	CREATE TABLE #temp(
		MASV nvarchar(15),
		MADK int,
		HOCKY int,
		TONGSOTC int,
		HOCPHI float
	)

	INSERT INTO #temp
	EXEC sp_XULYHOCPHI_select_all @MASV

	SELECT #temp.*, 			
			CASE 
			WHEN PHIEUTHU.SOTIENDONG is null THEN 0
			ELSE PHIEUTHU.SOTIENDONG
			END AS DADONG,
			CASE 
			WHEN #temp.HOCPHI - PHIEUTHU.SOTIENDONG is null THEN 0
			ELSE #temp.HOCPHI - PHIEUTHU.SOTIENDONG
			END AS CHUADONG
	FROM #temp LEFT JOIN PHIEUTHU ON #temp.MASV = PHIEUTHU.MASV AND #temp.HOCKY = PHIEUTHU.HOCKY
	WHERE #temp.HOCKY = @HOCKY
end
go

exec sp_XULYHOCPHI_byhocky '72DCHT20104', 2
