CREATE PROCEDURE sp_HOCPHI_insert(
	@MAHP nvarchar(10),
	@MASV nvarchar(10),
	@NIENKHOA nvarchar(9),
	@HOCKY int,
	@HOCPHI int
)
AS
BEGIN
	INSERT INTO HOCPHI VALUES (@MAHP, @MASV, @NIENKHOA, @HOCKY, @HOCPHI)
END
GO

CREATE PROCEDURE sp_HOCPHI_update(
	@MAHP nvarchar(10),
	@MASV nvarchar(10),
	@NIENKHOA nvarchar(9),
	@HOCKY int,
	@HOCPHI int
)
AS
BEGIN
	UPDATE HOCPHI SET MASV = @MASV, NIENKHOA = @NIENKHOA, HOCKY = @HOCKY, HOCPHI = @HOCPHI WHERE MAHP = @MAHP
END
GO

CREATE PROCEDURE sp_HOCPHI_delete(
	@MAHP nvarchar(10)
)
AS
BEGIN
	DELETE FROM HOCPHI WHERE MAHP = @MAHP
END
GO

CREATE PROCEDURE sp_HOCPHI_select_all
AS
BEGIN
	SELECT * FROM HOCPHI
END
GO

CREATE PROCEDURE sp_HOCPHI_select_mahp(
	@MAHP nvarchar(10)
)
AS
BEGIN
	SELECT * FROM HOCPHI WHERE MAHP = @MAHP
END
GO
