CREATE PROCEDURE sp_DONGHOCPHI_insert(
	@MADHP nvarchar(10),
	@MASV nvarchar(10),
	@NIENKHOA nvarchar(9),
	@HOCKY int,
	@NGAYDONG date,
	@SOTIENDONG int
)
AS
BEGIN
	INSERT INTO DONGHOCPHI VALUES (@MADHP, @MASV, @NIENKHOA, @HOCKY, @NGAYDONG, @SOTIENDONG)
END
GO

CREATE PROCEDURE sp_DONGHOCPHI_update(
	@MADHP nvarchar(10),
	@MASV nvarchar(10),
	@NIENKHOA nvarchar(9),
	@HOCKY int,
	@NGAYDONG date,
	@SOTIENDONG int
)
AS
BEGIN
	UPDATE DONGHOCPHI SET MASV = @MASV, NIENKHOA = @NIENKHOA, HOCKY = @HOCKY, NGAYDONG = @NGAYDONG, SOTIENDONG = @SOTIENDONG WHERE MADHP = @MADHP
END
GO

CREATE PROCEDURE sp_DONGHOCPHI_delete(
	@MADHP nvarchar(10)
)
AS
BEGIN
	DELETE FROM DONGHOCPHI WHERE MADHP = @MADHP
END
GO

CREATE PROCEDURE sp_DONGHOCPHI_select_all
AS
BEGIN
	SELECT * FROM DONGHOCPHI
END
GO

CREATE PROCEDURE sp_DONGHOCPHI_select_madhp(
	@MADHP nvarchar(10)
)
AS
BEGIN
	SELECT * FROM DONGHOCPHI WHERE MADHP = @MADHP
END
GO
