USE QLSV_TC
GO

CREATE PROCEDURE sp_LOPHOCPHAN_insert(
    @NIENKHOA nvarchar(9),
    @HOCKY int,
    @MAMH nvarchar(10),
    @MAGV nvarchar(10),
    @MACN nvarchar(10),
    @HUYLOP bit
)
AS
BEGIN
    INSERT INTO LOPHOCPHAN (NIENKHOA, HOCKY, MAMH, MAGV, MACN, HUYLOP)
    VALUES (@NIENKHOA, @HOCKY, @MAMH, @MAGV, @MACN, @HUYLOP)
END
GO

CREATE PROCEDURE sp_LOPHOCPHAN_update(
    @MALHP int,
    @NIENKHOA nvarchar(9),
    @HOCKY int,
    @MAMH nvarchar(10),
    @MAGV nvarchar(10),
    @MACN nvarchar(10),
    @HUYLOP bit
)
AS
BEGIN
    UPDATE LOPHOCPHAN SET NIENKHOA = @NIENKHOA, HOCKY = @HOCKY, MAMH = @MAMH, MAGV = @MAGV, MACN = @MACN, HUYLOP = @HUYLOP
    WHERE MALHP = @MALHP
END
GO

CREATE PROCEDURE sp_LOPHOCPHAN_delete(
    @MALHP int
)
AS
BEGIN
    DELETE FROM LOPHOCPHAN WHERE MALHP = @MALHP
END
GO

CREATE PROCEDURE sp_LOPHOCPHAN_select_all
AS
BEGIN
    SELECT * FROM LOPHOCPHAN
END
GO

CREATE PROCEDURE sp_LOPHOCPHAN_select_malhp(
    @MALHP int
)
AS
BEGIN
    SELECT * FROM LOPHOCPHAN WHERE MALHP = @MALHP
END
GO