USE QLSV_TC
GO

CREATE PROCEDURE sp_CTPHIEUTHU_insert(
	@MAPT int,
	@NGAYDONG datetime,
	@SOTIENDONG float
)
AS
BEGIN
INSERT INTO CTPHIEUTHU(MAPT, NGAYDONG, SOTIENDONG) VALUES (@MAPT, @NGAYDONG, @SOTIENDONG)
END
GO

CREATE PROCEDURE sp_CTPHIEUTHU_update(
	@MACTPT int,
	@MAPT int,
	@NGAYDONG datetime,
	@SOTIENDONG float
)
AS
BEGIN
UPDATE CTPHIEUTHU SET MAPT = @MAPT, NGAYDONG = @NGAYDONG, SOTIENDONG = @SOTIENDONG WHERE MACTPT = @MACTPT
END
GO

CREATE PROCEDURE sp_CTPHIEUTHU_delete(
	@MACTPT int
)
AS
BEGIN
DELETE FROM CTPHIEUTHU WHERE MACTPT = @MACTPT
END
GO

CREATE PROCEDURE sp_CTPHIEUTHU_select_all
AS
BEGIN
SELECT * FROM CTPHIEUTHU
END
GO

CREATE PROCEDURE sp_CTPHIEUTHU_select_mactpt(
	@MACTPT int
)
AS
BEGIN
SELECT * FROM CTPHIEUTHU WHERE MACTPT = @MACTPT
END
GO

CREATE PROCEDURE sp_CTPHIEUTHU_select_mapt(
	@MAPT int
)
AS
BEGIN
SELECT * FROM CTPHIEUTHU WHERE MAPT = @MAPT
END
GO