USE QLSV_TC
GO

CREATE PROCEDURE sp_CHUYENNGANH_insert (
	@MACN nvarchar(10),
	@TENCN nvarchar(50),
	@MAKHOA nvarchar(10)
)
AS
BEGIN
	INSERT INTO CHUYENNGANH (MACN, TENCN, MAKHOA)
	VALUES (@MACN, @TENCN, @MAKHOA)
END
GO

CREATE PROCEDURE sp_CHUYENNGANH_update (
	@MACN nvarchar(10),
	@TENCN nvarchar(50),
	@MAKHOA nvarchar(10)
)
AS
BEGIN
	UPDATE CHUYENNGANH
	SET TENCN = @TENCN, MAKHOA = @MAKHOA
	WHERE MACN = @MACN
END
GO

CREATE PROCEDURE sp_CHUYENNGANH_delete (
	@MACN nvarchar(10)
)
AS
BEGIN
	DELETE FROM CHUYENNGANH WHERE MACN = @MACN
END
GO

CREATE PROCEDURE sp_CHUYENNGANH_select_all
AS
BEGIN
	SELECT * FROM CHUYENNGANH
END
GO

CREATE PROCEDURE sp_CHUYENNGANH_select_macn (
	@MACN nvarchar(10)
)
AS
BEGIN
	SELECT * FROM CHUYENNGANH WHERE MACN = @MACN
END
GO

CREATE PROCEDURE sp_CHUYENNGANH_select_by_makhoa(
	@MAKHOA nvarchar(10)
)
AS
BEGIN
	SELECT *
	FROM CHUYENNGANH
	WHERE CHUYENNGANH.MAKHOA = @MAKHOA
END
GO
